// Auto-generated from Wayback URL audit. Old WordPress URLs → new site paths.
// Source-of-truth: Wayback Machine CDX index for nicolemickle.com captured pre-2026-05-04.

export type Redirect = { source: string; destination: string; permanent: true };

export const legacyRedirects: Redirect[] = [
  // Old root-path blog posts → /blog/<slug>. SEO authority preserved.
  { source: "/1371-cavender-creek-rd", destination: "/blog/1371-cavender-creek-rd", permanent: true },
  { source: "/223-s-ortman-dr-in-orlando", destination: "/blog/223-s-ortman-dr-in-orlando", permanent: true },
  { source: "/4-tips-to-sell-your-home-without-a-real-estate-agent-in-record-time", destination: "/blog/4-tips-to-sell-your-home-without-a-real-estate-agent-in-record-time", permanent: true },
  { source: "/5-tips-to-choose-a-top-notch-realtor-agent-when-buying-or-selling-your-home", destination: "/blog/5-tips-to-choose-a-top-notch-realtor-agent-when-buying-or-selling-your-home", permanent: true },
  { source: "/5-ways-to-add-color-to-your-home-exterior", destination: "/blog/5-ways-to-add-color-to-your-home-exterior", permanent: true },
  { source: "/5-ways-to-add-custom-to-your-kitchen", destination: "/blog/5-ways-to-add-custom-to-your-kitchen", permanent: true },
  { source: "/54-56-bougainvillea-dr", destination: "/blog/54-56-bougainvillea-dr", permanent: true },
  { source: "/6-design-ideas-to-add-luxury-to-your-new-construction-home", destination: "/blog/6-design-ideas-to-add-luxury-to-your-new-construction-home", permanent: true },
  { source: "/6-ways-to-convert-a-spare-bedroom", destination: "/blog/6-ways-to-convert-a-spare-bedroom", permanent: true },
  { source: "/902-nicole-drive", destination: "/blog/902-nicole-drive", permanent: true },
  { source: "/airbnb-business-in-florida", destination: "/blog/airbnb-business-in-florida", permanent: true },
  { source: "/are-new-construction-homes-negotiable", destination: "/blog/are-new-construction-homes-negotiable", permanent: true },
  { source: "/baldwin-park", destination: "/blog/baldwin-park", permanent: true },
  { source: "/bathroom-staging-tips", destination: "/blog/bathroom-staging-tips", permanent: true },
  { source: "/beaches-close-to-orlando", destination: "/blog/beaches-close-to-orlando", permanent: true },
  { source: "/benefits-of-buying-new-construction", destination: "/blog/benefits-of-buying-new-construction", permanent: true },
  { source: "/best-day-trips-from-orlando", destination: "/blog/best-day-trips-from-orlando", permanent: true },
  { source: "/best-flooring-for-new-construction", destination: "/blog/best-flooring-for-new-construction", permanent: true },
  { source: "/best-kitchen-staging-tips", destination: "/blog/best-kitchen-staging-tips", permanent: true },
  { source: "/best-places-to-buy-a-vacation-home-in-florida", destination: "/blog/best-places-to-buy-a-vacation-home-in-florida", permanent: true },
  { source: "/best-restaurants-in-lake-nona", destination: "/blog/best-restaurants-in-lake-nona", permanent: true },
  { source: "/best-things-to-do-lake-nona", destination: "/blog/best-things-to-do-lake-nona", permanent: true },
  { source: "/block-construction-vs-wood-frame", destination: "/blog/block-construction-vs-wood-frame", permanent: true },
  { source: "/blog-topics-for-realtors", destination: "/blog/blog-topics-for-realtors", permanent: true },
  { source: "/buyer-agent-vs-seller-agent", destination: "/blog/buyer-agent-vs-seller-agent", permanent: true },
  { source: "/cash-offer-in-real-estate", destination: "/blog/cash-offer-in-real-estate", permanent: true },
  { source: "/celebration-florida", destination: "/blog/celebration-florida", permanent: true },
  { source: "/central-florida-lakefront-homes", destination: "/blog/central-florida-lakefront-homes", permanent: true },
  { source: "/charming-towns-close-to-orlando", destination: "/blog/charming-towns-close-to-orlando", permanent: true },
  { source: "/clermont-florida", destination: "/blog/clermont-florida", permanent: true },
  { source: "/closing-costs-on-new-construction", destination: "/blog/closing-costs-on-new-construction", permanent: true },
  { source: "/closing-date-on-new-construction", destination: "/blog/closing-date-on-new-construction", permanent: true },
  { source: "/communities-of-orlando", destination: "/blog/communities-of-orlando", permanent: true },
  { source: "/condo-for-sale-in-south-pasadena", destination: "/blog/condo-for-sale-in-south-pasadena", permanent: true },
  { source: "/corporate-executives-relocation", destination: "/blog/corporate-executives-relocation", permanent: true },
  { source: "/custom-home-building-checklist", destination: "/blog/custom-home-building-checklist", permanent: true },
  { source: "/dining-details-and-tablescapes", destination: "/blog/dining-details-and-tablescapes", permanent: true },
  { source: "/downsizing-tips", destination: "/blog/downsizing-tips", permanent: true },
  { source: "/downtown-orlando", destination: "/blog/downtown-orlando", permanent: true },
  { source: "/dr-phillips-neighborhood-guide", destination: "/blog/dr-phillips-neighborhood-guide", permanent: true },
  { source: "/dr-phillips-vs-windermere", destination: "/blog/dr-phillips-vs-windermere", permanent: true },
  { source: "/everything-you-need-to-know-about-lake-nona-medical", destination: "/blog/everything-you-need-to-know-about-lake-nona-medical", permanent: true },
  { source: "/features-to-include-in-your-new-build", destination: "/blog/features-to-include-in-your-new-build", permanent: true },
  { source: "/first-real-estate-client", destination: "/blog/first-real-estate-client", permanent: true },
  { source: "/florida-pros-and-cons", destination: "/blog/florida-pros-and-cons", permanent: true },
  { source: "/florida-real-estate-trends", destination: "/blog/florida-real-estate-trends", permanent: true },
  { source: "/for-sale-1719-carnelian", destination: "/blog/for-sale-1719-carnelian", permanent: true },
  { source: "/for-sale-1731-carnelian-st", destination: "/blog/for-sale-1731-carnelian-st", permanent: true },
  { source: "/for-sale-1918-arden-oaks", destination: "/blog/for-sale-1918-arden-oaks", permanent: true },
  { source: "/hamlin-village-winter-garden", destination: "/blog/hamlin-village-winter-garden", permanent: true },
  { source: "/home-builders-in-orlando", destination: "/blog/home-builders-in-orlando", permanent: true },
  { source: "/home-for-sale-clermont", destination: "/blog/home-for-sale-clermont", permanent: true },
  { source: "/home-for-sale-deland-florida", destination: "/blog/home-for-sale-deland-florida", permanent: true },
  { source: "/home-for-sale-in-horizon-west", destination: "/blog/home-for-sale-in-horizon-west", permanent: true },
  { source: "/home-staging-tips", destination: "/blog/home-staging-tips", permanent: true },
  { source: "/horizon-west-community-guide", destination: "/blog/horizon-west-community-guide", permanent: true },
  { source: "/horizon-west-vs-lake-nona", destination: "/blog/horizon-west-vs-lake-nona", permanent: true },
  { source: "/how-i-help-healthcare-professionals-relocate-to-orlando", destination: "/blog/how-i-help-healthcare-professionals-relocate-to-orlando", permanent: true },
  { source: "/how-to-add-blue-to-your-home-decor", destination: "/blog/how-to-add-blue-to-your-home-decor", permanent: true },
  { source: "/how-to-design-your-kitchen-in-a-few-easy-steps", destination: "/blog/how-to-design-your-kitchen-in-a-few-easy-steps", permanent: true },
  { source: "/how-to-research-home-builder", destination: "/blog/how-to-research-home-builder", permanent: true },
  { source: "/hurricane-season-orlando", destination: "/blog/hurricane-season-orlando", permanent: true },
  { source: "/instagram-stories-for-real-estate", destination: "/blog/instagram-stories-for-real-estate", permanent: true },
  { source: "/kitchen-renovations", destination: "/blog/kitchen-renovations", permanent: true },
  { source: "/lake-mary", destination: "/blog/lake-mary", permanent: true },
  { source: "/lake-nona-events", destination: "/blog/lake-nona-events", permanent: true },
  { source: "/lawn-grass-in-florida", destination: "/blog/lawn-grass-in-florida", permanent: true },
  { source: "/listing-checklist-for-real-estate-agents", destination: "/blog/listing-checklist-for-real-estate-agents", permanent: true },
  { source: "/luxury-design-ideas", destination: "/blog/luxury-design-ideas", permanent: true },
  { source: "/master-planned-communities-in-florida", destination: "/blog/master-planned-communities-in-florida", permanent: true },
  { source: "/milk-district-guide", destination: "/blog/milk-district-guide", permanent: true },
  { source: "/minneola-neighborhood-guide", destination: "/blog/minneola-neighborhood-guide", permanent: true },
  { source: "/mistakes-when-buying-real-estate", destination: "/blog/mistakes-when-buying-real-estate", permanent: true },
  { source: "/monthly-mortgage-payment", destination: "/blog/monthly-mortgage-payment", permanent: true },
  { source: "/montverde-guide", destination: "/blog/montverde-guide", permanent: true },
  { source: "/moving-to-bonita-springs", destination: "/blog/moving-to-bonita-springs", permanent: true },
  { source: "/moving-to-florida-checklist", destination: "/blog/moving-to-florida-checklist", permanent: true },
  { source: "/moving-to-florida-from-california", destination: "/blog/moving-to-florida-from-california", permanent: true },
  { source: "/moving-to-lakeland-florida", destination: "/blog/moving-to-lakeland-florida", permanent: true },
  { source: "/moving-to-naples-florida", destination: "/blog/moving-to-naples-florida", permanent: true },
  { source: "/moving-to-ocala-florida", destination: "/blog/moving-to-ocala-florida", permanent: true },
  { source: "/moving-to-orlando", destination: "/blog/moving-to-orlando", permanent: true },
  { source: "/moving-to-st-augustine-florida", destination: "/blog/moving-to-st-augustine-florida", permanent: true },
  { source: "/moving-to-windermere", destination: "/blog/moving-to-windermere", permanent: true },
  { source: "/multigenerational-homes-in-orlando", destination: "/blog/multigenerational-homes-in-orlando", permanent: true },
  // /new-construction is a real route on the new site — no redirect. The
  // Sanity post with this slug remains reachable at /blog/new-construction.
  { source: "/new-construction-homes-in-clermont", destination: "/blog/new-construction-homes-in-clermont", permanent: true },
  { source: "/new-construction-real-estate-agent", destination: "/blog/new-construction-real-estate-agent", permanent: true },
  { source: "/new-construction-schedule-inspection", destination: "/blog/new-construction-schedule-inspection", permanent: true },
  { source: "/new-construction-walkthrough", destination: "/blog/new-construction-walkthrough", permanent: true },
  { source: "/nicole-mickle-redfin-feature", destination: "/blog/nicole-mickle-redfin-feature", permanent: true },
  { source: "/nobody-tells-you-moving-to-orlando", destination: "/blog/nobody-tells-you-moving-to-orlando", permanent: true },
  { source: "/one-level-homes-vs-two-story-homes", destination: "/blog/one-level-homes-vs-two-story-homes", permanent: true },
  { source: "/onx-homes", destination: "/blog/onx-homes", permanent: true },
  { source: "/orlando-gated-communities", destination: "/blog/orlando-gated-communities", permanent: true },
  { source: "/orlando-historic-neighborhoods", destination: "/blog/orlando-historic-neighborhoods", permanent: true },
  { source: "/packing-district-orlando", destination: "/blog/packing-district-orlando", permanent: true },
  { source: "/paint-colors-for-staging", destination: "/blog/paint-colors-for-staging", permanent: true },
  { source: "/pay-schedule-for-new-construction", destination: "/blog/pay-schedule-for-new-construction", permanent: true },
  { source: "/pinterest-for-real-estate-agents", destination: "/blog/pinterest-for-real-estate-agents", permanent: true },
  { source: "/plant-street-market-downtown-winter-garden-fl", destination: "/blog/plant-street-market-downtown-winter-garden-fl", permanent: true },
  { source: "/property-taxes-on-new-construction", destination: "/blog/property-taxes-on-new-construction", permanent: true },
  { source: "/pros-and-cons-orlando", destination: "/blog/pros-and-cons-orlando", permanent: true },
  { source: "/purchasing-new-construction-home", destination: "/blog/purchasing-new-construction-home", permanent: true },
  { source: "/questions-to-ask-your-real-estate-agent-when-selling", destination: "/blog/questions-to-ask-your-real-estate-agent-when-selling", permanent: true },
  { source: "/real-estate-captions", destination: "/blog/real-estate-captions", permanent: true },
  { source: "/real-estate-investment-in-florida", destination: "/blog/real-estate-investment-in-florida", permanent: true },
  // Was an Elementor service-pitch page; closest topical post on new site.
  { source: "/real-estate-marketing-strategy", destination: "/blog/seller-leads", permanent: true },
  { source: "/real-estate-quotes", destination: "/blog/real-estate-quotes", permanent: true },
  { source: "/realtor-for-new-construction", destination: "/blog/realtor-for-new-construction", permanent: true },
  { source: "/relocating-to-dr-phillips-florida", destination: "/blog/relocating-to-dr-phillips-florida", permanent: true },
  { source: "/retirement-communities-central-florida", destination: "/blog/retirement-communities-central-florida", permanent: true },
  { source: "/sanford-florida", destination: "/blog/sanford-florida", permanent: true },
  { source: "/scott-key-dr-winter-garden", destination: "/blog/scott-key-dr-winter-garden", permanent: true },
  { source: "/sell-your-home", destination: "/blog/sell-your-home", permanent: true },
  { source: "/seller-leads", destination: "/blog/seller-leads", permanent: true },
  { source: "/selling-your-orlando-home", destination: "/blog/selling-your-orlando-home", permanent: true },
  { source: "/small-towns-in-central-florida", destination: "/blog/small-towns-in-central-florida", permanent: true },
  { source: "/steps-to-buy-a-house-in-florida", destination: "/blog/steps-to-buy-a-house-in-florida", permanent: true },
  { source: "/the-powder-room", destination: "/blog/the-powder-room", permanent: true },
  { source: "/things-nobody-tells-you-about-moving-to-florida", destination: "/blog/things-nobody-tells-you-about-moving-to-florida", permanent: true },
  { source: "/things-that-influence-homebuyers", destination: "/blog/things-that-influence-homebuyers", permanent: true },
  { source: "/things-to-do-after-you-purchased-your-new-build", destination: "/blog/things-to-do-after-you-purchased-your-new-build", permanent: true },
  { source: "/things-to-do-windermere-florida", destination: "/blog/things-to-do-windermere-florida", permanent: true },
  { source: "/tips-to-choose-a-top-notch-realtor", destination: "/blog/tips-to-choose-a-top-notch-realtor", permanent: true },
  { source: "/top-10-summer-activities-for-the-orlando-area-teens", destination: "/blog/top-10-summer-activities-for-the-orlando-area-teens", permanent: true },
  { source: "/townhomes-investment", destination: "/blog/townhomes-investment", permanent: true },
  { source: "/ultimate-outdoor-living-in-windermere-florida", destination: "/blog/ultimate-outdoor-living-in-windermere-florida", permanent: true },
  { source: "/vacant-land-in-florida", destination: "/blog/vacant-land-in-florida", permanent: true },
  { source: "/vacation-home-in-florida", destination: "/blog/vacation-home-in-florida", permanent: true },
  { source: "/virtual-home-tours-near-orlando", destination: "/blog/virtual-home-tours-near-orlando", permanent: true },
  { source: "/walkable-communities-in-orlando", destination: "/blog/walkable-communities-in-orlando", permanent: true },
  { source: "/ways-to-add-natural-elements-to-your-home-decor", destination: "/blog/ways-to-add-natural-elements-to-your-home-decor", permanent: true },
  { source: "/ways-to-invest-in-florida-real-estate", destination: "/blog/ways-to-invest-in-florida-real-estate", permanent: true },
  { source: "/what-is-for-sale-by-owner", destination: "/blog/what-is-for-sale-by-owner", permanent: true },
  { source: "/what-you-need-to-know-about-back-to-school-shopping-in-orlando", destination: "/blog/what-you-need-to-know-about-back-to-school-shopping-in-orlando", permanent: true },
  { source: "/windermere-luxury-home-for-sale", destination: "/blog/windermere-luxury-home-for-sale", permanent: true },
  { source: "/winter-garden-florida", destination: "/blog/winter-garden-florida", permanent: true },
  { source: "/winter-garden-vs-horizon-west", destination: "/blog/winter-garden-vs-horizon-west", permanent: true },
  { source: "/winter-park-guide", destination: "/blog/winter-park-guide", permanent: true },
  { source: "/winter-springs-florida", destination: "/blog/winter-springs-florida", permanent: true },
  { source: "/your-swimming-pool-design-needs-one-of-these-water-features", destination: "/blog/your-swimming-pool-design-needs-one-of-these-water-features", permanent: true },

  // Old pages → new-site equivalents.
  { source: "/about-nicole-mickle", destination: "/about", permanent: true },
  { source: "/buy-an-orlando-home", destination: "/relocating", permanent: true },
  { source: "/deals", destination: "/blog", permanent: true },
  { source: "/florida-relocation", destination: "/relocating", permanent: true },
  { source: "/instagram-tips", destination: "/blog/instagram-stories-for-real-estate", permanent: true },
  { source: "/new-construction-homes-in-orlando", destination: "/new-construction", permanent: true },
  { source: "/news", destination: "/blog", permanent: true },
  { source: "/orlando-quiz", destination: "/quiz", permanent: true },
  { source: "/privacy-policy", destination: "/privacy", permanent: true },
  { source: "/sell-your-florida-home", destination: "/blog/sell-your-home", permanent: true },
  { source: "/terms-and-conditions", destination: "/terms", permanent: true },
  { source: "/work-with-me", destination: "/about", permanent: true },

  // One-off referenced in an old post body but never a real WP URL.
  { source: "/contact-nicole", destination: "/contact", permanent: true },

  // Topical category archives → matching new-site hub pages. More specific
  // rules MUST come before the wildcard /category/:path* fallback.
  { source: "/category/orlando-real-estate/relocation/:path*", destination: "/relocating", permanent: true },
  { source: "/category/orlando-real-estate/new-construction/:path*", destination: "/new-construction", permanent: true },
  { source: "/category/orlando-real-estate/neighborhood-guides/:path*", destination: "/neighborhoods", permanent: true },

  // WordPress feeds → new RSS feed (RSS subscribers + Google's discovered feeds).
  { source: "/feed", destination: "/blog/rss.xml", permanent: true },
  { source: "/feed/:path*", destination: "/blog/rss.xml", permanent: true },
  { source: "/comments/feed/:path*", destination: "/blog/rss.xml", permanent: true },

  // WordPress sitemaps → new sitemap.
  { source: "/wp-sitemap.xml", destination: "/sitemap.xml", permanent: true },
  { source: "/wp-sitemap-:path*.xml", destination: "/sitemap.xml", permanent: true },
  { source: "/sitemap_index.xml", destination: "/sitemap.xml", permanent: true },

  // Root pagination from a few WP themes.
  { source: "/page/:n", destination: "/blog", permanent: true },

  // Everything else under category / author / tag / paginated blog index → /blog.
  { source: "/category/:path*", destination: "/blog", permanent: true },
  { source: "/author/:path*", destination: "/blog", permanent: true },
  { source: "/tag/:path*", destination: "/blog", permanent: true },
  { source: "/blog/page/:n", destination: "/blog", permanent: true },
];
