import { defineField, defineType } from "sanity";

/**
 * Contact page singleton. Editable: hero copy, interest checkboxes,
 * contact info (phone/email/office), success message, location section.
 * Form labels stay hardcoded — they're standard and rarely change.
 */
export const contactPage = defineType({
  name: "contactPage",
  title: "Contact Page",
  type: "document",
  groups: [
    { name: "hero", title: "Hero", default: true },
    { name: "form", title: "Form" },
    { name: "info", title: "Contact info" },
    { name: "location", title: "Location section" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "heroEyebrow",
      title: "Small label above headline",
      type: "string",
      group: "hero",
      initialValue: "Contact",
      validation: (r) => r.required().max(40),
    }),
    defineField({
      name: "heroHeadlineLine1",
      title: "Headline — line 1",
      description: 'Currently "Let\'s start a".',
      type: "string",
      group: "hero",
      validation: (r) => r.required().max(60),
    }),
    defineField({
      name: "heroHeadlineLine2",
      title: "Headline — line 2 (italic)",
      description: 'Currently "conversation".',
      type: "string",
      group: "hero",
      validation: (r) => r.required().max(60),
    }),
    defineField({
      name: "heroBody",
      title: "Hero body",
      type: "text",
      rows: 3,
      group: "hero",
      validation: (r) => r.required().max(400),
    }),
    defineField({
      name: "interestOptions",
      title: "Interest checkboxes",
      description:
        "What the visitor can select on the form. Each item should be a short phrase. Drag to reorder.",
      type: "array",
      of: [{ type: "string", validation: (r) => r.max(60) }],
      group: "form",
      validation: (r) => r.min(2).max(10),
    }),
    defineField({
      name: "submitLabel",
      title: "Submit button text",
      type: "string",
      group: "form",
      initialValue: "Send message",
      validation: (r) => r.required().max(40),
    }),
    defineField({
      name: "successHeading",
      title: "After-submit heading",
      type: "string",
      group: "form",
      initialValue: "Thank you",
      validation: (r) => r.required().max(60),
    }),
    defineField({
      name: "successBody",
      title: "After-submit body",
      type: "text",
      rows: 2,
      group: "form",
      validation: (r) => r.required().max(200),
    }),
    defineField({
      name: "phoneNumber",
      title: "Phone number",
      description: "Displayed and used in the tel: link.",
      type: "string",
      group: "info",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "phoneDisplay",
      title: "Phone — displayed format",
      description: 'Shown to visitors. e.g. "(407) 353-0826".',
      type: "string",
      group: "info",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "email",
      title: "Email address",
      type: "string",
      group: "info",
      validation: (r) => r.required().email(),
    }),
    defineField({
      name: "officeName",
      title: "Office / brokerage name",
      type: "string",
      group: "info",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "locationEyebrow",
      title: "Small label above location heading",
      type: "string",
      group: "location",
      initialValue: "Based In",
      validation: (r) => r.max(40),
    }),
    defineField({
      name: "locationHeadline",
      title: "Location headline",
      description: 'Currently "Windermere, Florida".',
      type: "string",
      group: "location",
      validation: (r) => r.required().max(80),
    }),
    defineField({
      name: "locationBody",
      title: "Location body",
      type: "text",
      rows: 3,
      group: "location",
      validation: (r) => r.required().max(400),
    }),
    defineField({
      name: "seoTitle",
      title: "Browser tab / search title",
      type: "string",
      group: "seo",
      validation: (r) => r.max(70),
    }),
    defineField({
      name: "seoDescription",
      title: "Search description",
      type: "text",
      rows: 3,
      group: "seo",
      validation: (r) => r.max(200),
    }),
  ],
  preview: { prepare: () => ({ title: "Contact Page" }) },
});
