import { defineField, defineType } from "sanity";

/**
 * Quiz page singleton. Only the surrounding *copy* lives here — the
 * quiz questions, scoring logic, and option values stay in code because
 * changing a value would silently break the scoring algorithm.
 */
export const quizPage = defineType({
  name: "quizPage",
  title: "Quiz Page",
  type: "document",
  groups: [
    { name: "intro", title: "Intro", default: true },
    { name: "results", title: "Results screen" },
    { name: "emailCapture", title: "Email capture" },
    { name: "success", title: "Success message" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "introEyebrow",
      title: "Small label above heading",
      description: 'All-caps. Currently "Neighborhood Quiz".',
      type: "string",
      group: "intro",
      initialValue: "Neighborhood Quiz",
      validation: (r) => r.required().max(40),
    }),
    defineField({
      name: "introHeadingLine1",
      title: "Heading — line 1",
      description: 'Top line. Currently "Find your Orlando".',
      type: "string",
      group: "intro",
      validation: (r) => r.required().max(60),
    }),
    defineField({
      name: "introHeadingLine2",
      title: "Heading — line 2 (italic)",
      description: 'Italic. Currently "neighborhood".',
      type: "string",
      group: "intro",
      validation: (r) => r.required().max(60),
    }),
    defineField({
      name: "introBody",
      title: "Intro subhead",
      description: "1–2 short sentences explaining what's about to happen.",
      type: "text",
      rows: 3,
      group: "intro",
      validation: (r) => r.required().max(300),
    }),
    defineField({
      name: "startButtonLabel",
      title: "Start button label",
      description: 'Currently "Start the quiz".',
      type: "string",
      group: "intro",
      initialValue: "Start the quiz",
      validation: (r) => r.required().max(40),
    }),
    defineField({
      name: "resultsEyebrow",
      title: "Small label above results heading",
      type: "string",
      group: "results",
      initialValue: "Your Results",
      validation: (r) => r.max(40),
    }),
    defineField({
      name: "resultsHeading",
      title: "Results heading",
      description: 'Currently "Your top Orlando neighborhoods".',
      type: "string",
      group: "results",
      validation: (r) => r.required().max(80),
    }),
    defineField({
      name: "resultsBody",
      title: "Results body",
      type: "text",
      rows: 3,
      group: "results",
      validation: (r) => r.required().max(300),
    }),
    defineField({
      name: "emailHeading",
      title: "Email capture heading",
      type: "string",
      group: "emailCapture",
      validation: (r) => r.required().max(80),
    }),
    defineField({
      name: "emailBody",
      title: "Email capture body",
      type: "text",
      rows: 3,
      group: "emailCapture",
      validation: (r) => r.required().max(300),
    }),
    defineField({
      name: "emailPlaceholder",
      title: "Email field placeholder",
      type: "string",
      group: "emailCapture",
      initialValue: "your@email.com",
      validation: (r) => r.required().max(40),
    }),
    defineField({
      name: "successHeading",
      title: "Success heading",
      description: 'After they submit. Currently "Check your inbox".',
      type: "string",
      group: "success",
      validation: (r) => r.required().max(60),
    }),
    defineField({
      name: "successBody",
      title: "Success body",
      type: "text",
      rows: 2,
      group: "success",
      validation: (r) => r.required().max(200),
    }),
    defineField({
      name: "seoTitle",
      title: "Browser tab / search title",
      type: "string",
      group: "seo",
      validation: (r) => r.max(70),
    }),
    defineField({
      name: "seoDescription",
      title: "Search description",
      type: "text",
      rows: 3,
      group: "seo",
      validation: (r) => r.max(200),
    }),
  ],
  preview: { prepare: () => ({ title: "Quiz Page" }) },
});
